package org.qbroker.node;

/* EventMonitor.java - a MessageNode monitoring and tracking events */

import java.util.HashMap;
import java.util.Map;
import java.util.Iterator;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;
import java.lang.reflect.InvocationTargetException;
import javax.jms.Message;
import javax.jms.TextMessage;
import javax.jms.JMSException;
import org.qbroker.common.XQueue;
import org.qbroker.common.Browser;
import org.qbroker.common.AssetList;
import org.qbroker.common.TimeWindows;
import org.qbroker.common.CollectibleCells;
import org.qbroker.monitor.ConfigList;
import org.qbroker.jms.MessageUtils;
import org.qbroker.jms.MessageFilter;
import org.qbroker.jms.JMSEvent;
import org.qbroker.jms.TextEvent;
import org.qbroker.node.Node;
import org.qbroker.node.NodeUtils;
import org.qbroker.event.EventEscalation;
import org.qbroker.event.EventSelector;
import org.qbroker.event.Event;

/**
 * EventMonitor monitors incoming JMS events and keeps tracking their states
 * according to the rulesets and the content of the aggregated events.
 * In case that the state changes up to a certain point, EventMonitor will
 * generate a new JMS event as the escalation.  All escalation events will
 * be routed to the outlink of done.  For all the incoming events, EventMonitor
 * routes them into three outlinks: bypass for all the processed incoming
 * events, nohit for those events do not belong to any rulesets, failure for
 * the incoming events failed in the process. However, the outlink of done
 * can be shared with other outlinks.
 *<br/><br/>
 * EventMonitor contains a number of predefined rulesets.  These rulesets
 * categorize incoming events into non-overlapping groups.  Therefore, each
 * ruleset defines a unique event group.  It contains the name of the rule,
 * and an EventSelector to select events for the group.  If PreferredOutLink
 * is defined in the ruleset, it is treated as a bypassing ruleset.
 * Otherwise, the ruleset should define ClassName as to instantiate the
 * instance of EventEscalation.  For each incomiong event, EventMonitor will
 * match it against every EventSelectors to single out a ruleset.  If the
 * ruleset is an instance of EventEscalation, EventMonitor will invoke its
 * public method of escalate() to evalaute the event.  The instance of
 * EventEscalation is supposed to maintain the states of the event group.
 * In case that a state change is up to certain point, an escalation event
 * will be generated by the method of escalate().  This event will contain
 * details of the state change.  It will be delivered according to the
 * predefined order.
 *<br/><br/>
 * EventMonitor always creates one extra ruleset, nohit.  The ruleset of nohit
 * is for those events not hitting any patterns.  Please remember that there is
 * no one-to-one relationship between the candidate events and the esacaltion
 * events.  The number of escalation events for a ruleset is stored into its
 * RULE_PEND field.  For a ruleset, its property displaying and resetting
 * are mutual-exclusively determined by DisplayMask and StringProperty for
 * the ruleset.  If DisplayMask is not defined in a ruleset or it is set to 0
 * or -1 (by default), its StringProperty will be used to reset the string
 * properties on the escalation events.  Otherwise, its StringProperty will
 * only be used to display the details of escalation events.  On the node
 * level, DisplayMask and StringProperty control the displaying result of
 * all incoming events.  If the DisplayMask of a ruleset is set to -1, that
 * rule will inherit the DisplayMask and the StringProperty from the node
 * for display control on the rule level.
 *<br/><br/>
 * You are free to choose any names for the four fixed outlinks.  But
 * EventMonitor always assumes the first outlink for done, the second for
 * bypass, the third for failure and the last for nohit.  Any two or more
 * outlinks can share the same outlink name. It means these outlinks are
 * sharing the same output channel.
 *<br/>
 * @author yannanlu@yahoo.com
 */

public class EventMonitor extends Node {
    private long heartbeat = 3600000;
    private int[] outLinkMap;

    private final static int RESULT_OUT = 0;
    private final static int BYPASS_OUT = 1;
    private final static int FAILURE_OUT = 2;
    private final static int NOHIT_OUT = 3;

    public EventMonitor(Map props) {
        super(props);
        Object o;
        List list;
        String key;
        Browser browser;
        Map<String, Object> rule;
        Map ph;
        long[] outInfo, ruleInfo;
        long tm;
        int i, j, n, ruleSize = 512;
        StringBuffer strBuf = new StringBuffer();

        if ((o = props.get("Operation")) != null)
            operation = (String) o;
        else
            operation = "escalate";
        if ((o = props.get("MaxNumberRule")) != null)
            ruleSize = Integer.parseInt((String) o);
        if (ruleSize <= 0)
            ruleSize = 512;

        if ((o = props.get("OutLink")) == null || !(o instanceof List))
            throw(new IllegalArgumentException(name +
                ": OutLink is not well defined"));

        list = (List) o;
        n = list.size();

        tm = System.currentTimeMillis();

        int[] overlap = new int[]{BYPASS_OUT, FAILURE_OUT, NOHIT_OUT};
        assetList = NodeUtils.initFixedOutLinks(tm, capacity, n, overlap,
            name, list);
        outLinkMap = new int[]{RESULT_OUT, BYPASS_OUT, FAILURE_OUT, NOHIT_OUT};
        outLinkMap[BYPASS_OUT] = overlap[0];
        outLinkMap[FAILURE_OUT] = overlap[1];
        outLinkMap[NOHIT_OUT] = overlap[2];

        if (assetList == null)
            throw(new IllegalArgumentException(name +
                ": failed to init OutLinks"));

        browser = assetList.browser();
        while ((i = browser.next()) >= 0) {
            outInfo = assetList.getMetaData(i);
            if (outInfo[OUT_OFFSET] < 0 || outInfo[OUT_LENGTH] < 0 ||
                (outInfo[OUT_LENGTH]==0 && outInfo[OUT_OFFSET]!=0) ||
                outInfo[OUT_LENGTH] + outInfo[OUT_OFFSET] >
                outInfo[OUT_CAPACITY])
                throw(new IllegalArgumentException(name +
                    ": OutLink Partition is not well defined for " +
                    assetList.getKey(i)));
            if ((debug & DEBUG_INIT) > 0)
                strBuf.append("\n\t" + assetList.getKey(i) + ": " + i + " " +
                    outInfo[OUT_CAPACITY] + " " + outInfo[OUT_OFFSET] +
                    "," + outInfo[OUT_LENGTH]);
        }

        if ((debug & DEBUG_INIT) > 0) {
            new Event(Event.DEBUG, name + " LinkName: OID Capacity Partition " +
                " - " + linkName + " " + capacity + strBuf.toString()).send();
            strBuf = new StringBuffer();
        }

        if (outLinkMap[NOHIT_OUT] >= assetList.size())
            throw(new IllegalArgumentException(name+": missing some OutLinks"));

        cfgList = new AssetList(name, 64);
        msgList = new AssetList(name, capacity);
        ruleList = new AssetList(name, ruleSize);
        cells = new CollectibleCells(name, capacity);

        if ((o = props.get("Ruleset")) != null && o instanceof List)
            list = (List) o;
        else
            list = new ArrayList();
        n = list.size();

        try { // init rulesets
            String str;
            ConfigList cfg;
            int k, m;
            // for nohit
            key = "nohit";
            ruleInfo = new long[RULE_TIME + 1];
            for (i=0; i<=RULE_TIME; i++)
                ruleInfo[i] = 0;
            ruleInfo[RULE_STATUS] = NODE_RUNNING;
            ruleInfo[RULE_DMASK] = displayMask;
            ruleInfo[RULE_TIME] = tm;
            ruleInfo[RULE_OID] = outLinkMap[NOHIT_OUT];
            ruleInfo[RULE_PID] = TYPE_BYPASS;
            rule = new HashMap<String, Object>();
            rule.put("Name", key);
            rule.put("PropertyName", displayPropertyName);
            ruleList.add(key, ruleInfo, rule);
            outInfo = assetList.getMetaData(outLinkMap[NOHIT_OUT]);
            outInfo[OUT_NRULE] ++;
            outInfo[OUT_ORULE] ++;

            for (i=0; i<n; i++) { // for defined rules
                o = list.get(i);
                if (o instanceof String) {
                    o = props.get((String) o);
                    if (o == null || !(o instanceof Map)) {
                        new Event(Event.ERR, name + ": ruleset " + i + ", " +
                            (String)list.get(i)+", is not well defined").send();
                        continue;
                    }
                }
                ph = (Map) o;
                if((o = ph.get("RuleType")) == null || !(o instanceof String) ||
                    !"ConfigList".equals((String) o)) {
                    ruleInfo = new long[RULE_TIME+1];
                    rule = initRuleset(tm, ph, ruleInfo);
                    if(rule != null && (key=(String) rule.get("Name")) != null){
                        if(ruleList.add(key, ruleInfo, rule) < 0)//failed to add
                            new Event(Event.ERR, name + ": ruleset " + i + ", "+
                                key + ", failed to be added").send();
                    }
                    else
                        new Event(Event.ERR, name + ": ruleset " + i +
                            " failed to be initialized").send();
                    continue;
                }
                try { // for external rules via ConfigList
                    cfg = new ConfigList(ph);
                }
                catch (Exception ex) {
                    new Event(Event.ERR, name + ": ConfigList " + i +
                        " failed to be initialized").send();
                    continue;
                }
                key = cfg.getName();
                cfg.setDataField(name);
                cfg.loadList();
                k = cfg.getSize();
                m = cfgList.add(key, new long[]{k, 0}, cfg);
                if (m < 0) {
                    new Event(Event.ERR, name + ": ConfigList " + key +
                        " failed to be added to the list").send();
                    cfg.close();
                    continue;
                }
                for (j=0; j<k; j++) { // init all external rulesets
                    str = cfg.getItem(j);
                    ph = cfg.getProps(str);
                    key = cfg.getKey(j);
                    ruleInfo = new long[RULE_TIME+1];
                    try {
                        rule = initRuleset(tm, ph, ruleInfo);
                    }
                    catch (Exception ex) {
                        new Event(Event.ERR, name + ": ConfigList " +
                            cfg.getName()+" failed to init external rule "+key+
                            " at " + j + ": " + Event.traceStack(ex)).send();
                        continue;
                    }
                    if (rule != null && rule.size() > 0) {
                        if(ruleList.add(key, ruleInfo, rule) < 0)//failed to add
                            new Event(Event.ERR, name + ": ConfigList " +
                                cfg.getName()+ " failed to add external rule " +
                                key + " at " + j).send();
                    }
                    else
                        new Event(Event.ERR, name + ": ConfigList " +
                            cfg.getName()+ " failed to init external rule "+
                            key + " at " + j).send();
                }
            }
        }
        catch (Exception e) {
            throw(new IllegalArgumentException(name + ": failed to init rule "+
                i + ": " + Event.traceStack(e)));
        }

        if ((debug & DEBUG_INIT) > 0) {
            browser = ruleList.browser();
            while ((i = browser.next()) >= 0) {
                ruleInfo = ruleList.getMetaData(i);
                strBuf.append("\n\t" + ruleList.getKey(i) + ": " + i + " " +
                    ruleInfo[RULE_PID] + " " + ruleInfo[RULE_EXTRA] + " " +
                    ruleInfo[RULE_TTL]/1000 + " " + ruleInfo[RULE_DMASK] + " "+
                    ruleInfo[RULE_OPTION] + " - " +
                    assetList.getKey((int) ruleInfo[RULE_OID]));
            }
            new Event(Event.DEBUG, name+
                " RuleName: RID PID EXTRA TTL DMASK OPTION - OutName" +
                strBuf.toString()).send();
        }
    }

    /**
     * It initializes a new ruleset with the ruleInfo and returns the rule upon
     * success.  Otherwise, it throws an exception or returns null.
     */
    protected Map<String, Object> initRuleset(long tm, Map ph, long[] ruleInfo){
        Object o;
        Map<String, Object> rule;
        Iterator iter;
        List list;
        String key, str, ruleName, preferredOutName;
        long[] outInfo;
        int i, k, n, id;

        if (ph == null || ph.size() <= 0)
            throw(new IllegalArgumentException("Empty property for a rule"));
        if (ruleInfo == null || ruleInfo.length <= RULE_TIME)
            throw(new IllegalArgumentException("ruleInfo is not well defined"));
        ruleName = (String) ph.get("Name");
        if (ruleName == null || ruleName.length() == 0)
            throw(new IllegalArgumentException("ruleName is not defined"));
        rule = new HashMap<String, Object>();
        rule.put("Name", ruleName);
        preferredOutName = (String) ph.get("PreferredOutLink");
        if(preferredOutName !=null && !assetList.containsKey(preferredOutName)){
            preferredOutName = assetList.getKey(outLinkMap[NOHIT_OUT]);
            new Event(Event.WARNING, name + ": OutLink for " +
                ruleName + " not well defined, use the default: "+
                preferredOutName).send();
        }

        for (i=0; i<=RULE_TIME; i++)
            ruleInfo[i] = 0;

        ruleInfo[RULE_STATUS] = NODE_RUNNING;
        ruleInfo[RULE_TIME] = tm;

        if ((o = ph.get("DisplayMask")) != null && o instanceof String)
            ruleInfo[RULE_DMASK] = Integer.parseInt((String) o);
        else
            ruleInfo[RULE_DMASK] = displayMask;

        // store escalation mask into RULE_OPTION
        if ((o = ph.get("EsclationMask")) != null)
            ruleInfo[RULE_OPTION] = Integer.parseInt((String) o);
        else
            ruleInfo[RULE_OPTION] = ruleInfo[RULE_DMASK];

        rule.put("Filter", new EventSelector(ph));
        if (preferredOutName != null) { // for bypass
            ruleInfo[RULE_OID] = assetList.getID(preferredOutName);
            ruleInfo[RULE_PID] = TYPE_BYPASS;
        }
        else { // for EventEscalation
            String className;
            java.lang.reflect.Constructor con;
            EventEscalation escalator = null;
            TimeWindows tw = null;
                
            if ((o = ph.get("ClassName")) != null && o instanceof String)
                className = (String) o;
            else // default escalation
                className = "org.qbroker.jms.EventEscalator";

            try {
                Class<?> cls = Class.forName(className);
                con = cls.getConstructor(new Class[]{Map.class});
                escalator = (EventEscalation) con.newInstance(new Object[]{ph});
                if ((o = ph.get("ActiveTime")) != null)
                    tw = new TimeWindows((Map) o);
            }
            catch (InvocationTargetException e) {
                Throwable ex = e.getTargetException();
                new Event(Event.ERR, name + ": failed to init " +
                    ruleName + ": " + Event.traceStack(ex));
                return null;
            }
            catch (Exception e) {
                new Event(Event.ERR, name + ": failed to init " +
                    ruleName + ": " + Event.traceStack(e));
                return null;
            }

            rule.put("Escalation", escalator);
            if (tw != null)
                rule.put("TimeWindows", tw);

            // escalation order stored in RULE_EXTRA
            ruleInfo[RULE_EXTRA] = escalator.getEscalationOrder();

            // action delay in ms stored in TTL
            if ((o = ph.get("ActionDelay")) != null)
                ruleInfo[RULE_TTL] = Long.parseLong((String) o);

            ruleInfo[RULE_OID] = outLinkMap[BYPASS_OUT];
            ruleInfo[RULE_PID] = TYPE_AGGREGATE;

        }
        outInfo = assetList.getMetaData((int) ruleInfo[RULE_OID]);
        outInfo[OUT_NRULE] ++;
        outInfo[OUT_ORULE] ++;

        // for StringProperty
        if ((o = ph.get("StringProperty")) != null && o instanceof Map) {
            iter = ((Map) o).keySet().iterator();
            k = ((Map) o).size();
            String[] pn = new String[k];
            k = 0;
            while (iter.hasNext()) {
                key = (String) iter.next();
                if ((pn[k] = MessageUtils.getPropertyID(key)) == null)
                    pn[k] = key;
                k ++;
            }
            rule.put("PropertyName", pn);
        }
        else if (o == null)
            rule.put("PropertyName", displayPropertyName);

        return rule;
    }

    /**
     * picks up a message from input queue and evaluates its content to
     * decide which output queue to propagate
     */
    public void propagate(XQueue in, XQueue[] out) throws JMSException {
        Message inMessage;
        TextEvent msg = null;
        Event event = null;
        String msgStr = null, ruleName = null;
        Object o;
        Object[] asset;
        String[] propertyName = null;
        EventSelector[] filter = null;
        EventEscalation escalator = null;
        TimeWindows tw = null;
        Browser browser;
        Map rule;
        int[] ruleMap;
        long[] outInfo, ruleInfo = null;
        long currentTime, previousTime, wt, count = 0;
        int mask, ii, sz, dspBody;
        int i = 0, m, n, previousRid;
        int rid = -1; // the rule id
        int cid = -1; // the cell id of the message in input queue
        int oid = 0; // the id of the output queue
        byte[] buffer = new byte[bufferSize];

        i = in.getCapacity();
        if (capacity != i) { // assume it only occurs at startup
            new Event(Event.WARNING, name + ": " + in.getName() +
                " has the different capacity of " + i + " from " +
                capacity).send();
            capacity = i;
            msgList.clear();
            msgList = new AssetList(name, capacity);
            cells.clear();
            cells = new CollectibleCells(name, capacity);
        }

        // initialize patterns
        m = ruleList.size();
        filter = new EventSelector[m];
        browser = ruleList.browser();
        ruleMap = new int[m];
        i = 0;
        while ((rid = browser.next()) >= 0) {
            rule = (Map) ruleList.get(rid);
            filter[i] = (EventSelector) rule.get("Filter");
            ruleMap[i++] = rid;
        }
        dspBody = MessageUtils.SHOW_BODY + MessageUtils.SHOW_SIZE;

        // update assetList
        n = out.length;
        for (i=0; i<n; i++) {
            asset = (Object[]) assetList.get(i);
            asset[ASSET_XQ] = out[i];
            outInfo = assetList.getMetaData(i);
            if (outInfo[OUT_CAPACITY] != out[i].getCapacity())
                outInfo[OUT_CAPACITY] = out[i].getCapacity();
        }

        previousTime = 0L;
        previousRid = -1;
        ii = 0;
        wt = 5L;
        sz = msgList.size();
        while (((mask = in.getGlobalMask()) & XQueue.KEEP_RUNNING) > 0) {
            if ((mask & XQueue.STANDBY) > 0) // standby temporarily
                break;
            if ((cid = in.getNextCell(wt)) < 0) {
                if (++ii >= 10) {
                    feedback(in, -1L);
                    sz = msgList.size();
                    if (sz <= 0)
                        wt = waitTime;
                    ii = 0;
                }
                else {
                    if (sz > 0)
                        feedback(in, -1L);
                    continue;
                }
            }
            currentTime = System.currentTimeMillis();
            if (currentTime - previousTime >= heartbeat) {
                if (update(currentTime) > 0) // reset session
                    currentTime = System.currentTimeMillis();
                previousTime = currentTime;
            }
            if (cid < 0)
                continue;

            wt = 5L;
            if ((inMessage = (Message) in.browse(cid)) == null) {
                in.remove(cid);
                new Event(Event.WARNING, name + ": " + Event.traceStack(
                   new JMSException("null msg from " + in.getName()))).send();
                continue;
            }

            currentTime = System.currentTimeMillis();
            event = null;
            if (inMessage instanceof JMSEvent) {
                event = (Event) inMessage;
            }
            else try { // copy the message into event
                event = (Event) MessageUtils.duplicate(inMessage, buffer);
            }
            catch (JMSException e) {
                new Event(Event.ERR, name + " failed to copy msg: " +
                    Event.traceStack(e)).send();
            }
            catch (Exception e) {
                new Event(Event.ERR, name + " failed to copy msg: " +
                    Event.traceStack(e)).send();
            }

            i = NOHIT_OUT;
            if (event == null) { // for failures
                i = FAILURE_OUT;
            }
            else if (event instanceof TextEvent) { // for TextEvent
                if (((TextEvent) event).getLogMode() != Event.LOG_JMS) try {
                    // not from toEvent, so set attribute of "text"
                    event.setPriority(event.getPriority());
                    event.setAttribute("text", ((TextEvent) event).getText());
                    ((TextEvent) event).setLogMode(Event.LOG_JMS);
                }
                catch (Exception e) {
                    new Event(Event.ERR, name + " failed to reset event: " +
                        Event.traceStack(e)).send();
                    i = FAILURE_OUT;
                }
            }

            rid = 0;
            if (i != FAILURE_OUT) { // evaluate the event with all rulesets
                int j;
                for (j=1; j<m; j++) {
                    if (filter[j].evaluate(currentTime, event))
                        break;
                }
                rid = ruleMap[j%m];
            }

            if (rid != previousRid) {
                ruleName = ruleList.getKey(rid);
                ruleInfo = ruleList.getMetaData(rid);
                rule = (Map) ruleList.get(rid);
                propertyName = (String[]) rule.get("PropertyName");
                if (ruleInfo[RULE_PID] == TYPE_AGGREGATE) {
                    escalator = (EventEscalation) rule.get("Escalation");
                    tw = (TimeWindows) rule.get("TimeWindow");
                }
                previousRid = rid;
            }

            if (rid == 0) { // nohit or failure
                oid = outLinkMap[i];
            }
            else if (TYPE_NONE == ruleInfo[RULE_PID]) { // bypass
                oid = (int) ruleInfo[RULE_OID];
                i = -1;
            }
            else try { // for escalation
                i = (tw != null) ? tw.check(currentTime,0L):TimeWindows.NORMAL;
                msg = (TextEvent) escalator.escalate(i, currentTime, event);
                if (msg == null) // no escalation msg
                    i = BYPASS_OUT;
                else { // msg for escalation
                    if (ruleInfo[RULE_EXTRA] > 0) { // escalation first
                        oid = RESULT_OUT;
                        int k = flush(currentTime, cid, rid, msg, in, out[oid],
                            oid, buffer);
                        if (k <= 0)
                            new Event(Event.ERR, name + ": " + ruleName +
                                " failed to flush escalation msg at " +
                                cid).send();
                        else { // flush is done
                            long[] state = msgList.getMetaData(cid);
                            k = (int) state[MSG_BID];
                            do { // wait for its delivery to complete
                                if (out[oid].collect(waitTime, k) >= 0)
                                    break;
                                mask = in.getGlobalMask();
                            } while ((mask & XQueue.KEEP_RUNNING) > 0 &&
                                (mask & XQueue.STANDBY) == 0);
                            if (ruleInfo[RULE_TTL] > 0 && // for delay
                                (mask & XQueue.KEEP_RUNNING) > 0 &&
                                (mask & XQueue.STANDBY) == 0) try {
                                Thread.sleep(ruleInfo[RULE_TTL]);
                            }
                            catch (Exception e) {
                            }
                        }
                    }
                    i = BYPASS_OUT;
                }
                oid = outLinkMap[i];
            }
            catch (Exception e) {
                String str = name + ": " + ruleName;
                Exception ex = null;
                if (e instanceof JMSException)
                    ex = ((JMSException) e).getLinkedException();
                if (ex != null)
                    str += " Linked exception: " + ex.toString() + "\n";
                i = FAILURE_OUT;
                oid = outLinkMap[i];
                new Event(Event.ERR, str + " failed to escalate msg: "+
                    Event.traceStack(e)).send();
            }
            catch (Error e) {
                String str = name + ": " + ruleName;
                new Event(Event.ERR, str + " failed to escalate msg: "+
                    e.toString()).send();
                if ((in.getGlobalMask() & XQueue.EXTERNAL_XA) > 0) try {
                    inMessage.acknowledge();
                }
                catch (Exception ex) {
                }
                catch (Error ex) {
                    in.remove(cid);
                    Event.flush(e);
                }
                in.remove(cid);
                Event.flush(e);
            }

            if ((debug & DEBUG_PROP) > 0)
                new Event(Event.DEBUG, name+" propagate: cid=" + cid +
                    " rid=" + rid + " oid=" + oid + " i=" + i).send();

            if (ruleInfo[RULE_DMASK] > 0) try { // display the message
                msgStr = null;
                if ((ruleInfo[RULE_DMASK] & dspBody) > 0)
                    msgStr = MessageUtils.processBody(inMessage, buffer);
                new Event(Event.INFO, name + ": " + ruleName+" checked msg " +
                    (count+1) +":"+ MessageUtils.display(inMessage, msgStr,
                    (int) ruleInfo[RULE_DMASK], propertyName)).send();
            }
            catch (Exception ex) {
                new Event(Event.WARNING, name + ": " + ruleName +
                    " failed to display msg: " + Event.traceStack(ex)).send();
            }

            count += passthru(currentTime, inMessage, in, rid, oid, cid, 0);
            if (ruleInfo[RULE_EXTRA] == 0 && msg != null) {
                oid = RESULT_OUT;
                i = flush(currentTime, cid, rid, msg, in, out[oid], oid,buffer);
                if (i <= 0)
                    new Event(Event.ERR, name + ": " + ruleName +
                        " failed to flush escalation msg at " + cid).send();
            }
            else if (ruleInfo[RULE_EXTRA] < 0 && msg != null) {
                if (msgList.existsID(cid)) // cache the escalation msg
                    o = msgList.set(cid, msg);
            }
            msg = null;
            feedback(in, -1L);
            sz = msgList.size();
            inMessage = null;
        }
    }

    /**
     * displays and sets properties on the escalation message according to
     * its ruleset and puts it to the specified outlink. It returns the number 
     * of messages flushed.
     */
    private int flush(long currentTime, int cid, int rid, Message msg,
        XQueue in, XQueue out, int oid, byte[] buffer) {
        int i, dmask;
        long[] ruleInfo;
        String ruleName;
        Map rule;
        String[] propertyName;

        if (msg == null) {
            new Event(Event.WARNING, name + " null msg in flush: cid=" + cid +
                " rid=" + rid + " oid=" + oid).send();
            return 0;
        }
        if ((debug & DEBUG_COLL) > 0)
            new Event(Event.DEBUG, name + " flush: cid=" + cid +
                " rid=" + rid + " oid=" + oid).send();

        ruleName = ruleList.getKey(rid);
        ruleInfo = ruleList.getMetaData(rid);
        rule = (Map) ruleList.get(rid);
        propertyName = (String[]) rule.get("PropertyName");
        // retrieve displayMask from RULE_OPTION
        dmask = (int) ruleInfo[RULE_OPTION];

        if (dmask != 0) try { // display the message
            String msgStr = null;
            if ((dmask & (MessageUtils.SHOW_BODY | MessageUtils.SHOW_SIZE)) > 0)
                msgStr = MessageUtils.processBody(msg, buffer);
            new Event(Event.INFO, name + ": " + ruleName +" escalated a msg: " +
                MessageUtils.display(msg, msgStr, dmask, propertyName)).send();
        }
        catch (Exception e) {
            new Event(Event.WARNING, name + ": " + ruleName +
                " failed to display msg: " + e.toString()).send();
        }

        // flush the escalation msg
        i = passthru(currentTime, msg, in, rid, oid, -1, 0);
        if (i > 0) { // update escalation count on the rule
            ruleInfo[RULE_PEND] ++;
            ruleInfo[RULE_TIME] = currentTime;
        }

        return i;
    }

    private int update(long currentTime) {
        StringBuffer strBuf = null;
        Browser browser;
        EventEscalation escalator;
        Map rule = null;
        long ht, mtime;
        int rid, n, count = 0;

        count = 0;
        browser = ruleList.browser();
        while ((rid = browser.next()) >= 0) {
            rule = (Map) ruleList.get(rid);
            escalator = (EventEscalation) rule.get("Escalator");
            if (escalator == null || escalator.getSessionSize() <= 0)
                continue;
            mtime = escalator.getSessionTime();
            if (currentTime - mtime >= heartbeat)
                count += escalator.resetSession(currentTime);
        }

        return count;
    }

    /**
     * It passes the message from the input XQueue over to an output XQueue and
     * returns 1 upon success or 0 otherwise. In case of cid < 0, the message
     * has nothing to do with the input XQueue. Nothing will be added to
     * msgList for tracking. No update on stats of ruleset either.
     */
    protected int passthru(long currentTime, Message msg, XQueue in,
        int rid, int oid, int cid, int tid) {
        Object[] asset = null;
        XQueue out;
        long[] state, outInfo, ruleInfo = null;
        int id = -1, k, mid, mask, len, shift, outCapacity;
        asset = (Object[]) assetList.get(oid);
        if (asset == null) {
            if (cid >= 0) // incoming msg
                k = in.putback(cid);
            else
                k = -1;
            new Event(Event.ERR, name + ": asset is null on " +
                assetList.getKey(oid) + " of " + oid + " for " +
                rid + " with msg at " + cid).send();
            try {
                Thread.sleep(500);
            }
            catch (Exception e) {
            }
            return 0;
        }
        out = (XQueue) asset[ASSET_XQ];
        outInfo = assetList.getMetaData(oid);
        len = (int) outInfo[OUT_LENGTH];
        switch (len) {
          case 0:
            shift = 0;
            for (k=0; k<1000; k++) { // reserve an empty cell
                id = out.reserve(-1L);
                if (id >= 0)
                    break;
                mask = in.getGlobalMask();
                if ((mask & XQueue.KEEP_RUNNING) == 0 ||
                    (mask & XQueue.STANDBY) > 0) // disabled or stopped
                    break;
                feedback(in, waitTime);
            }
            break;
          case 1:
            shift = (int) outInfo[OUT_OFFSET];
            for (k=0; k<1000; k++) { // reserve the empty cell
                id = out.reserve(-1L, shift);
                if (id >= 0)
                    break;
                mask = in.getGlobalMask();
                if ((mask & XQueue.KEEP_RUNNING) == 0 ||
                    (mask & XQueue.STANDBY) > 0) // disabled or stopped
                    break;
                feedback(in, waitTime);
            }
            break;
          default:
            shift = (int) outInfo[OUT_OFFSET];
            for (k=0; k<1000; k++) { // reserve an partitioned empty cell
                id = out.reserve(-1L, shift, len);
                if (id >= 0)
                    break;
                mask = in.getGlobalMask();
                if ((mask & XQueue.KEEP_RUNNING) == 0 ||
                    (mask & XQueue.STANDBY) > 0) // disabled or stopped
                    break;
                feedback(in, waitTime);
            }
            break;
        }
        outCapacity = (int) outInfo[OUT_CAPACITY];

        if (id >= 0 && id < outCapacity) { // id-th cell of out reserved
            String key = oid + "/" + id;
            mid = msgList.getID(key);
            if (mid < 0) { // id-th cell was empty before, add new entry to it
                if (cid >= 0) // incoming msg
                    mid = msgList.add(key, new long[]{cid, oid, id, rid,
                        tid, currentTime}, key, cid);
                else // generated msg
                    mid = -1;
            }
            else { // id-th cell has just been empty now, replace it
                Object o;
                cells.collect(-1L, mid);
                state = msgList.getMetaData(mid);
                o = msgList.remove(mid);
                in.remove(mid);
                outInfo[OUT_SIZE] --;
                outInfo[OUT_COUNT] ++;
                k = (int) state[MSG_RID];
                ruleInfo = ruleList.getMetaData(k);
                if (ruleInfo[RULE_EXTRA] < 0 && o instanceof Message) {
                    mask = in.getGlobalMask();
                    if(ruleInfo[RULE_TTL] > 0 && (mask & XQueue.STANDBY) == 0 &&
                        (mask & XQueue.KEEP_RUNNING) > 0) try { // for delay
                        Thread.sleep(ruleInfo[RULE_TTL]);
                    }
                    catch (Exception e) {
                    }
                    asset = (Object[]) assetList.get(RESULT_OUT);
                    int i = flush(currentTime, mid, k, (Message) o, in,
                        (XQueue) asset[ASSET_XQ], RESULT_OUT, new byte[4096]);
                    if (i <= 0)
                        new Event(Event.ERR, name + ": " + ruleList.getKey(k) +
                            " failed to flush escalation msg at " + mid).send();
                }
                ruleInfo[RULE_SIZE] --;
                ruleInfo[RULE_COUNT] ++;
                ruleInfo[RULE_TIME] = currentTime;
                if ((debug & DEBUG_FBAK) > 0)
                    new Event(Event.DEBUG, name+" passback: " + k + " " + mid +
                        ":" + state[MSG_CID] + " "+key+" "+ruleInfo[RULE_SIZE]+
                        " " + outInfo[OUT_SIZE] + " " + out.size() + ":" +
                        out.depth() + " " + msgList.size()).send();
                if (cid >= 0) // incoming msg
                    mid = msgList.add(key, new long[] {cid, oid, id, rid,
                        tid, currentTime}, key, cid);
                else // generated msg
                    mid = -1;
            }
            if (cid >= 0 && mid < 0) { // failed to add state info to msgList
                out.cancel(id);
                k = in.putback(cid);
                new Event(Event.ERR, name + ": failed to add to MSGLIST at " +
                    mid + ":" + cid + " with " + key + " for " +
                    ruleList.getKey(rid) + ": " + msgList.size()).send();
                return 0;
            }
            if (cid >= 0) { // incoming msg
                k = out.add(msg, id, cbw);
                ruleInfo = ruleList.getMetaData(rid);
                ruleInfo[RULE_SIZE] ++;
                ruleInfo[RULE_TIME] = currentTime;
                outInfo[OUT_SIZE] ++;
                if (outInfo[OUT_STATUS] == NODE_RUNNING)
                    outInfo[OUT_TIME] = currentTime;
            }
            else { // generated msg
                k = out.add(msg, id);
                outInfo[OUT_COUNT] ++;
                outInfo[OUT_TIME] = currentTime;
            }
            if ((debug & DEBUG_PASS) > 0) {
                if (cid < 0)
                    ruleInfo = ruleList.getMetaData(rid);
                new Event(Event.DEBUG, name+" passthru: " + rid + " " +
                    mid + ":" + cid + " " + key + " " + ruleInfo[RULE_SIZE] +
                    " " + outInfo[OUT_SIZE] + " " + out.size() + ":" +
                    out.depth() + " " + msgList.size()).send();
            }
        }
        else { // reservation failed
            if (cid >= 0) // incoming msg
                k = in.putback(cid);
            else // generated msg
                k = -1;
            ruleInfo = ruleList.getMetaData(rid);
            new Event(Event.WARNING, name + ": XQ is full on " +
                assetList.getKey(oid) + " of " + oid + " for " + rid +
                ": " + outInfo[OUT_QDEPTH] + "," + outInfo[OUT_SIZE] +
                ": " + out.size() + "," + out.depth() + " / " +
                ruleInfo[RULE_SIZE] + ": " + k).send();
            return 0;
        }
        return 1;
    }

    /**
     * It returns the number of done messages removed from the input XQueue.
     * If milliSec < 0, there is no wait and it tries to collect all cells.
     * Otherwise, it just tries to collect the first collectible cell.
     */
    protected int feedback(XQueue in, long milliSec) {
        Object o;
        Object[] asset;
        XQueue out;
        byte[] buffer = new byte[4096];
        int mid, rid, oid, id, l = 0;
        long[] state, outInfo, ruleInfo;
        long t, wt = 0L;
        StringBuffer strBuf = null;
        if ((debug & DEBUG_FBAK) > 0)
            strBuf = new StringBuffer();

        t = System.currentTimeMillis();
        while ((mid = cells.collect(milliSec)) >= 0) {
            state = msgList.getMetaData(mid);
            oid = (int) state[MSG_OID];
            asset = (Object[]) assetList.get(oid);
            if (asset == null)
                continue;
            out = (XQueue) asset[ASSET_XQ];
            id = (int) state[MSG_BID];
            in.remove(mid);
            o = msgList.remove(mid);
            outInfo = assetList.getMetaData(oid);
            outInfo[OUT_SIZE] --;
            outInfo[OUT_COUNT] ++;
            if (outInfo[OUT_STATUS] == NODE_RUNNING)
                outInfo[OUT_TIME] = t;
            rid = (int) state[MSG_RID];
            ruleInfo = ruleList.getMetaData(rid);
            // check for escalation msg
            if (ruleInfo[RULE_EXTRA] < 0 && o instanceof Message) {
                if (ruleInfo[RULE_TTL] > wt) { // for delay
                    int mask = in.getGlobalMask();
                    if ((mask & XQueue.KEEP_RUNNING) > 0 &&
                        (mask & XQueue.STANDBY) == 0) try {
                        Thread.sleep(ruleInfo[RULE_TTL] - wt);
                    }
                    catch (Exception e) {
                    }
                    // reset wt for its maximum value
                    wt = ruleInfo[RULE_TTL];
                }
                asset = (Object[]) assetList.get(RESULT_OUT);
                int i = flush(t, mid, rid, (Message) o, in,
                    (XQueue) asset[ASSET_XQ], RESULT_OUT, buffer);
                if (i <= 0)
                    new Event(Event.ERR, name + ": " + ruleList.getKey(rid) +
                        " failed to flush escalation msg at " + mid).send();
            }
            ruleInfo[RULE_SIZE] --;
            ruleInfo[RULE_COUNT] ++;
            ruleInfo[RULE_TIME] = t;
            if ((debug & DEBUG_FBAK) > 0)
                strBuf.append("\n\t" + rid + " " + mid + "/" + state[MSG_CID] +
                    " " + oid + ":" + id + " " + ruleInfo[RULE_SIZE] + " " +
                    outInfo[OUT_SIZE]+ " " + out.size() + "|" + out.depth() +
                    " " + msgList.size());
            l ++;
            if (milliSec >= 0) // only one collection a time
                break;
        }
        if (l > 0 && (debug & DEBUG_FBAK) > 0)
            new Event(Event.DEBUG, name + " feedback: RID MID/CID OID:ID " +
                "RS OS size|depth ms - " + l + " msgs fed back to " +
                in.getName() + " with " + in.size() + ":" + in.depth() +
                strBuf.toString()).send();

        return l;
    }

    /**
     * cleans up MetaData for all XQs and messages
     */
    public void resetMetaData(XQueue in, XQueue[] out) {
        Object[] asset;
        XQueue xq;
        Browser browser;
        long[] state;
        int[] list;
        int i, j, n, mid, oid, id, outCapacity;

        feedback(in, -1L);
        n = msgList.size();
        list = new int[n];
        n = msgList.queryIDs(list);
        for (i=0; i<n; i++) {
            mid = list[i];
            state = msgList.getMetaData(mid);
            oid = (int) state[MSG_OID];
            id = (int) state[MSG_BID];
            asset = (Object[]) assetList.get(oid);
            if (asset == null) {
                msgList.remove(mid);
                continue;
            }
            xq = (XQueue) asset[ASSET_XQ];
            if (xq != null) synchronized(xq) {
                if (xq.getCellStatus(id) == XQueue.CELL_OCCUPIED) {
                    xq.takeback(id);
                }
                else if (xq.getCellStatus(id) == XQueue.CELL_TAKEN) {
                    xq.remove(id);
                }
            }
            in.putback(mid);
            msgList.remove(mid);
        }

        browser = assetList.browser();
        while ((i = browser.next()) >= 0) {
            state = assetList.getMetaData(i);
            state[OUT_SIZE] = 0;
        }

        browser = ruleList.browser();
        while ((i = browser.next()) >= 0) {
            state = ruleList.getMetaData(i);
            state[RULE_SIZE] = 0;
        }
    }

    public void close() {
        Map rule;
        Browser browser;
        EventEscalation escalator;
        int rid;
        setStatus(NODE_CLOSED);
        cells.clear();
        msgList.clear();
        assetList.clear();
        browser = ruleList.browser();
        while((rid = browser.next()) >= 0) {
            rule = (Map) ruleList.get(rid);
            if (rule != null) {
                escalator = (EventEscalation) rule.get("Escalator");
                if (escalator != null)
                    escalator.clear();
                rule.clear();
            }
        }
        ruleList.clear();
        if (cfgList != null) {
            ConfigList cfg;
            browser = cfgList.browser();
            while((rid = browser.next()) >= 0) {
                cfg = (ConfigList) cfgList.get(rid);
                if (cfg != null)
                    cfg.close();
            }
            cfgList.clear();
        }
    }
}
